name: Format & Lint

on:
  push:

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: install dependecies
        working-directory: ./scene
        run: npm ci
      - name: build
        working-directory: ./scene
        run: npm run build
      - name: lint
        working-directory: ./scene
        run: npm run lint
      - name: format
        working-directory: ./scene
        run: npm run format
